### ISSUE TITLE
globus-connect-server-setup failure on Ubuntu 18.04

### ISSUE THREAD

**Issue by todorGaidarov** [globus/globus-connect-server#24]
Hi,
I got the following exception while trying to create endpoint with 
`sudo globus-connect-server-setup`
```
Traceback (most recent call last):
  File "/usr/bin/globus-connect-server-setup", line 14, in <module>
    load_entry_point('globus-connect-server==4.0.59', 'console_scripts', 'globus-connect-server-setup')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/globus/connect/server/__init__.py", line 36, in <module>
    from globus_sdk import (
  File "/usr/share/globus-connect-server-common/globus_sdk/__init__.py", line 3, in <module>
    from globus_sdk.auth import AuthClient, ConfidentialAppAuthClient, NativeAppAuthClient
  File "/usr/share/globus-connect-server-common/globus_sdk/auth/__init__.py", line 1, in <module>
    from globus_sdk.auth.client_types import (
  File "/usr/share/globus-connect-server-common/globus_sdk/auth/client_types/__init__.py", line 1, in <module>
    from globus_sdk.auth.client_types.base import AuthClient
  File "/usr/share/globus-connect-server-common/globus_sdk/auth/client_types/base.py", line 9, in <module>
    from globus_sdk.auth.token_response import OAuthTokenResponse
  File "/usr/share/globus-connect-server-common/globus_sdk/auth/token_response.py", line 5, in <module>
    import jwt
ModuleNotFoundError: No module named 'jwt'
```

I followed the instructions from [here](https://docs.globus.org/globus-connect-server/v4/#debian_ubuntu).

**Comment by todorGaidarov** [comment]
I had to install globus-sdk to resolve the problem
`pip3 install globus-sdk`
I didn't see it mentioned in the [Globus Connect Server Prerequisites](https://docs.globus.org/globus-connect-server/v4/#globus_connect_server_prerequisites).
It might be worth adding to the docs.
