### ISSUE TITLE
globus-connect-server-setup fails when GCS is configured to use CILogon auth on CentOS 6

### ISSUE THREAD

**Issue by danpowers** [globus/globus-connect-server#4]
see https://globusonline.zendesk.com/agent/tickets/305699

User reports globus-connect-server-setup fails when attempting to configure GCS to use CILogon based auth on CentOS 6. Was able to reproduce issue on clean CentOS 6 image with GCS 4.0.35 - see below:

```
# python --version

Python 2.6.6

# grep -v "^$\|^;" /etc/globus-connect-server.conf

[Globus]
User = %(GLOBUS_USER)s
Password = %(GLOBUS_PASSWORD)s
[Endpoint]
Name = ticket305699 
Public = False
DefaultDirectory = /~/
[Security]
FetchCredentialFromRelay = True
IdentityMethod = CILogon
CILogonIdentityProvider = University of Chicago
[GridFTP]
Server = %(HOSTNAME)s
RestrictPaths =
[MyProxy]
[OAuth]

# globus-connect-server-setup -v

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/globus/connect/server/setup.py", line 132, in <module>
    conf = ConfigFile(config_file=conf_filename, root=root)
  File "/usr/lib/python2.6/site-packages/globus/connect/server/configfile.py", line 370, in __init__
    self.validate_cilogon_identity_provider()
  File "/usr/lib/python2.6/site-packages/globus/connect/server/configfile.py", line 405, in validate_cilogon_identity_provider
    % cilogon_idp)
  File "/usr/lib64/python2.6/xml/etree/ElementTree.py", line 330, in find
    return ElementPath.find(self, path)
  File "/usr/lib64/python2.6/xml/etree/ElementPath.py", line 186, in find
    return _compile(path).find(element)
  File "/usr/lib64/python2.6/xml/etree/ElementPath.py", line 176, in _compile
    p = Path(path)
  File "/usr/lib64/python2.6/xml/etree/ElementPath.py", line 93, in __init__
    "expected path separator (%s)" % (op or tag)
SyntaxError: expected path separator ([)
```

**Comment by michaellink** [comment]
Fixed in 4.0.36 and released to stable repo.
