### ISSUE TITLE
globus-connect-server-setup fails when GCS is configured to use OAuth on RHEL 7.2

### ISSUE THREAD

**Issue by danpowers** [globus/globus-connect-server#6]
Discovered in:

https://globusonline.zendesk.com/agent/tickets/305945

NOTE: Issue does NOT show up on CentOS 7.2

GCS=4.0.36-1

```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

# grep -v "^$\|^;" /etc/globus-connect-server.conf
[Globus]
User = %(GLOBUS_USER)s
Password = %(GLOBUS_PASSWORD)s
[Endpoint]
Name = %(SHORT_HOSTNAME)s
Public = False
DefaultDirectory = /~/
[Security]
FetchCredentialFromRelay = True
IdentityMethod = OAuth
[GridFTP]
Server = %(HOSTNAME)s
RestrictPaths =
[MyProxy]
Server = %(HOSTNAME)s
[OAuth]
Server = %(HOSTNAME)s

# globus-connect-server-setup -v

...

EXIT: GCMU.configure_trust_roots()
ENTER: GCMU.restart()
restarting with /etc/init.d/httpd restart
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/globus/connect/server/setup.py", line 138, in <module>
    web.setup()
  File "/usr/lib/python2.7/site-packages/globus/connect/server/web/__init__.py", line 108, in setup
    self.restart(**kwargs)
  File "/usr/lib/python2.7/site-packages/globus/connect/server/__init__.py", line 856, in restart
    restarter = Popen(args, stdin = None, stdout=PIPE, stderr=PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by bester** [comment]
I think this is fixed in 4.0.38 (currently in unstable)
